### ISSUE TITLE
How to configue the Xplane Data Input&output?

### ISSUE THREAD

**Issue by ludviglee** [MaxFerretti/XPlaneConnector#12]
Hi ,Max
I want to know how to configue the Xplane? I ran the example, but nothing changed in xplane,and no strings appear in textbox.

**Comment by MaxFerretti** [comment]
Hello,
there shouldn't be any configuration in XPlane, the XPlaneConnector will subscribe to the requested DataRefs once you call Start.
You can try and check in the XPlane configuration if the default port has been changed, it should be 49000.
Try to launch XPlane and select a simple aircraft (like the C172)
Run the example program and press Start.

**Comment by ludviglee** [comment]
Hi Max,
I test the example like you said above,but nothing changed. My X-plane version is 10.02, Is there any difference with your version?

**Comment by MaxFerretti** [comment]
I tested my code with X-Plane 11.
X-Plane 10 have the same DataRef structure, some DataRefs has been added in later version but the ones I use in the example program are the same in X-Plane 10.
I checked it for Versione 10.41 because I couldn't find an older version.
You could check in this folder:
<XPlane install dir>\Resources\plugins
There should be a file DataRefs.txt
Check if the following lines exists within this file:
sim/cockpit/electrical/battery_on
sim/cockpit/radios/nav1_freq_hz
sim/aircraft/view/acf_tailnum

**Comment by ludviglee** [comment]
Thank you Max, I changed to x-plane11, now it works. But I have another question. How do I set the ail rud ele and throttle to a specific value directly?

**Comment by MaxFerretti** [comment]
You just have to find the DataRefs you want to set and call:
connector.SetDataRefValue(DataRefElement dataref, float value)
