### ISSUE TITLE
Just some clarifications...

### ISSUE THREAD

**Issue by raysot** [MaxFerretti/XPlaneConnector#17]
Your work is perfect for a project I'm working on with X-Plane.

I have just a few questions:

1. in the line below, what does the "25" stand for? Is it arbitrary or does it have a useful meaning?

connector.Subscribe(XPlaneConnector.DataRefs.CockpitRadiosNav1FreqHz, 25, (element, value) => {Log($"{element.DataRef}: {value}");});

2. I need to subscribe to a rather large subset of Datarefs. Is there a way to subscribe to all of them without having to write a line of code for each dataref? Or, can I subscribe to all of them with just a few lines of code? Or even better, could I subscribe to all the "**OperationFailuresRel *** " datarefs in a few lines of code?

I can't begin to tell you how appreciative I am for your work here. Thank You!
Ray S.
raysot @ Comcast.net

**Comment by MaxFerretti** [comment]
Hello,
thank you, I'm glad you appreciate my library.

About your questions:
1. the "25" you see on that line is the frequency, it tells the library about how many times per second X-Plane must update the DataRef.
The library handles all the communications, and informs you only when the value actually changes.
For examples, on that line you request X-Plane to send the info about Nav1 Hz 25 times per second, the callback will only be called when the Nav1 Hz actually changes.

2. Since you must provide a callback to handle the values, there's no massive subscription method by now.
Moreover I didn't find a wildcard option to subscribe to X-Plane, I will check it out in the next versions if it will be implemented and eventually I will update the library to handle it.
I think a workaround you could use is declaring a generic callback that can handle all types of values you need, then defining an array with all the DataRefs you want to subscribe to and Subscribe in a loop.

```
foreach(var dr in MassiveDataRefArray)
{
   connector.Subscribe(dr, 25, GenericDRHandler);
}
```

Then

```
private void GenericDRHandler(DataRefElement element, float value)
{
    switch(element.DataRef)
    {
         case "sim/cockpit/radios/nav1_freq_hz":
          break;
          /* ... */
      }
}
```


Let me know if that helps, if you have further questions feel free to contact me again.
